rancherTurtles:
  image: controller
  imageVersion: v0.0.0
  imagePullPolicy: Never
  namespace: rancher-turtles-system
  managerArguments: []
  imagePullSecrets: []
  features:
    embedded-capi:
      disabled: true
    rancher-webhook:
      cleanup: true
      kubectlImage: rancher/kubectl
    rancher-kubeconfigs:
      label: true
cluster-api-operator:
  enabled: true
  cert-manager:
    enabled: false
  volumes:
    - name: cert
      secret:
        defaultMode: 420
        secretName: capi-operator-webhook-service-cert
    - name: clusterctl-config
      configMap:
        name: clusterctl-config
  volumeMounts:
    manager:
      - mountPath: /tmp/k8s-webhook-server/serving-certs
        name: cert
        readOnly: true
      - mountPath: /config
        name: clusterctl-config
        readOnly: true
  cluster-api:
    enabled: true
    configSecret:
      name: ""
      defaultName: capi-env-variables
    core:
      namespace: capi-system
      fetchConfig:
        url: ""
        selector: ""
    kubeadmBootstrap:
      namespace: capi-kubeadm-bootstrap-system
      fetchConfig:
        url: ""
        selector: ""
    kubeadmControlPlane:
      namespace: capi-kubeadm-control-plane-system
      fetchConfig:
        url: ""
        selector: ""
