namespace: "{{ .Values.rancherTurtles.namespace }}"
images:
- name: controller
  newName: "{{ .Values.rancherTurtles.image }}"
  newTag: "{{ .Values.rancherTurtles.tag }}"
namePrefix: rancher-turtles-
bases:
- ../rbac
