---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-turtles-cattle-io-capi-cattle-io-v1alpha1-capiprovider
  failurePolicy: Fail
  name: mcapiprovider.kb.io
  rules:
  - apiGroups:
    - turtles.cattle.io.capi.cattle.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capiproviders
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-turtles-cattle-io-capi-cattle-io-v1alpha1-capiprovider
  failurePolicy: Fail
  name: vcapiprovider.kb.io
  rules:
  - apiGroups:
    - turtles.cattle.io.capi.cattle.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capiproviders
  sideEffects: None
