# permissions for end users to view capiproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: capiprovider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rancher-turtles
    app.kubernetes.io/part-of: rancher-turtles
    app.kubernetes.io/managed-by: kustomize
  name: capiprovider-viewer-role
rules:
- apiGroups:
  - turtles.cattle.io.capi.cattle.io
  resources:
  - capiproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - turtles.cattle.io.capi.cattle.io
  resources:
  - capiproviders/status
  verbs:
  - get
