{{- if .Values.clusterAPI.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "1"
  name: {{ .Values.clusterAPI.core.namespace }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: {{ .Values.clusterAPI.core.namespace }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  version: {{ $.Values.clusterAPI.version }}
  additionalManifests:
    name: capi-additional-rbac-roles
    namespace: {{ .Values.clusterAPI.core.namespace }}
{{- if $.Values.clusterAPI.configSecret.name }}
  secretName: {{ $.Values.clusterAPI.configSecret.name }}
{{- if $.Values.clusterAPI.configSecret.namespace }}
  secretNamespace: {{ $.Values.clusterAPI.configSecret.namespace }}
{{- end }}
{{- end }}
{{- if or $.Values.clusterAPI.core.fetchConfig.url $.Values.clusterAPI.core.fetchConfig.selector }}
  fetchConfig:
    {{- if $.Values.clusterAPI.core.fetchConfig.url }}
    url: {{ $.Values.clusterAPI.core.fetchConfig.url }}
    {{- end }}
    {{- if $.Values.clusterAPI.core.fetchConfig.selector }}
    selector: {{ $.Values.clusterAPI.core.fetchConfig.selector }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capi-additional-rbac-roles
  namespace: {{ .Values.clusterAPI.core.namespace }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
data: 
  manifests: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-machine-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke-machine.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
{{- end }}
