name: Run e2e tests

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  RANCHER_PASSWORD: ${{ secrets.RANCHER_PASSWORD }}

jobs:
  e2e:
    concurrency: test-e2e
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setupGo
      uses: actions/setup-go@v4
      with:
        go-version: '=1.20.7'
    - name: Run e2e tests
      run: ISOLATED_MODE=true make test-e2e
    - name: Collect run artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: _artifacts
