name: Run nightly e2e tests

on:
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:

concurrency: ci_e2e_tests

env:
  NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
  NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
  RANCHER_HOSTNAME: ${{ secrets.NGROK_DOMAIN }}
  RANCHER_PASSWORD: ${{ secrets.RANCHER_PASSWORD }}
  CAPA_ENCODED_CREDS: ${{ secrets.CAPA_ENCODED_CREDS }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  e2e_import_gitops:
      uses: ./.github/workflows/run-e2e-suite.yaml
      with:
        test_suite: $(pwd)/test/e2e/suites/import-gitops
        test_name: Import via GitOps
        run_azure_janitor: false
        artifact_name: artifacts_import_gitops
      secrets: inherit
  e2e_v2prov:
      if: ${{ always() }}
      needs: e2e_import_gitops
      uses: ./.github/workflows/run-e2e-suite.yaml
      with:
        test_suite: $(pwd)/test/e2e/suites/v2prov
        test_name: v2 provisioning
        run_azure_janitor: true
        artifact_name: artifacts_v2prov
      secrets: inherit
  e2e_update_labels:
      if: ${{ always() }}
      needs: e2e_v2prov
      uses: ./.github/workflows/run-e2e-suite.yaml
      with:
        test_suite: $(pwd)/test/e2e/suites/update-labels
        test_name: Update labels
        run_azure_janitor: true
        artifact_name: artifacts_update_labels
      secrets: inherit
  e2e_embedded_capi_disabled:
      if: ${{ always() }}
      needs: e2e_update_labels
      uses: ./.github/workflows/run-e2e-suite.yaml
      with:
        test_suite: $(pwd)/test/e2e/suites/embedded-capi-disabled
        test_name: Update labels
        run_azure_janitor: false
        artifact_name: artifacts_embedded_capi
      secrets: inherit