name: Lint and Test Charts

on: pull_request

env:
  TAG: v0.0.1
  RELEASE_TAG: v0.0.1
  MANIFEST_IMG: controller
  CONTROLLER_IMG: controller
  PULL_POLICY: Never

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
        with:
          version: v3.9.0

      - name: setupGo
        uses: actions/setup-go@v4
        with:
          go-version: '=1.20.7'

      - name: Build docker image
        run: make docker-build

      - name: Add CAPI operator chart repo
        run: helm repo add capi-operator https://kubernetes-sigs.github.io/cluster-api-operator

      - name: Package operator chart
        run: make release-chart

      - name: Run chart-testing (lint)
        run: ct lint --validate-maintainers=false --charts out/charts/rancher-turtles/

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind

      - name: Add local docker image
        run: kind load docker-image ${{ env.MANIFEST_IMG }}:${{ env.TAG }}

      - name: Run chart-testing (install)
        run: helm install rancher-turtles out/charts/rancher-turtles/ -n rancher-turtles-system --create-namespace --wait --set cluster-api-operator.cert-manager.enabled=true

      - name: Run chart-testing (un-install)
        run: helm uninstall rancher-turtles -n rancher-turtles-system --wait
